create table if not exists public.categories (
    id bigint generated by default as identity primary key,
    name text not null,
    emoji text not null default '📁',
    color text not null default '#0ea5e9',
    audio_url text,
    speak_enabled boolean not null default true,
    parent_id bigint references public.categories(id) on delete cascade,
    sort_order integer not null default 0
);

alter table public.categories add column if not exists audio_url text;
alter table public.categories add column if not exists speak_enabled boolean not null default true;

create table if not exists public.words (
    id bigint generated by default as identity primary key,
    category_id bigint not null references public.categories(id) on delete cascade,
    word text not null,
    phrase text,
    emoji text not null default '💬',
    color text not null default '#0ea5e9',
    audio_url text,
    sort_order integer not null default 0
);

alter table public.words add column if not exists audio_url text;

alter table public.categories enable row level security;
alter table public.words enable row level security;

grant usage, select on all sequences in schema public to anon, authenticated;
grant select, insert, update, delete on public.categories to anon, authenticated;
grant select, insert, update, delete on public.words to anon, authenticated;

drop policy if exists "public read categories" on public.categories;
create policy "public read categories" on public.categories for select to anon, authenticated using (true);

drop policy if exists "public insert categories" on public.categories;
create policy "public insert categories" on public.categories for insert to anon, authenticated with check (true);

drop policy if exists "public update categories audio" on public.categories;
create policy "public update categories audio" on public.categories for update to anon, authenticated using (true) with check (true);

drop policy if exists "public delete categories" on public.categories;
create policy "public delete categories" on public.categories for delete to anon, authenticated using (true);

drop policy if exists "public read words" on public.words;
create policy "public read words" on public.words for select to anon, authenticated using (true);

drop policy if exists "public insert words" on public.words;
create policy "public insert words" on public.words for insert to anon, authenticated with check (true);

drop policy if exists "public update words audio" on public.words;
create policy "public update words audio" on public.words for update to anon, authenticated using (true) with check (true);

drop policy if exists "public delete words" on public.words;
create policy "public delete words" on public.words for delete to anon, authenticated using (true);

insert into storage.buckets (id, name, public)
values ('word-audio', 'word-audio', true)
on conflict (id) do update set public = true;

drop policy if exists "public read word audio" on storage.objects;
create policy "public read word audio" on storage.objects for select to anon, authenticated using (bucket_id = 'word-audio');

drop policy if exists "public insert word audio" on storage.objects;
create policy "public insert word audio" on storage.objects for insert to anon, authenticated with check (bucket_id = 'word-audio');

drop policy if exists "public update word audio" on storage.objects;
create policy "public update word audio" on storage.objects for update to anon, authenticated using (bucket_id = 'word-audio') with check (bucket_id = 'word-audio');

insert into storage.buckets (id, name, public)
values ('sentence-audio', 'sentence-audio', true)
on conflict (id) do update set public = true;

drop policy if exists "public read sentence audio" on storage.objects;
create policy "public read sentence audio" on storage.objects for select to anon, authenticated using (bucket_id = 'sentence-audio');

drop policy if exists "public insert sentence audio" on storage.objects;
create policy "public insert sentence audio" on storage.objects for insert to anon, authenticated with check (bucket_id = 'sentence-audio');

drop policy if exists "public update sentence audio" on storage.objects;
create policy "public update sentence audio" on storage.objects for update to anon, authenticated using (bucket_id = 'sentence-audio') with check (bucket_id = 'sentence-audio');

drop policy if exists "public delete sentence audio" on storage.objects;
create policy "public delete sentence audio" on storage.objects for delete to anon, authenticated using (bucket_id = 'sentence-audio');

create table if not exists public.sentence_items (
    id text primary key,
    text text not null,
    audio_url text,
    created_at timestamptz not null default now()
);

alter table public.sentence_items enable row level security;

grant select, insert, update, delete on public.sentence_items to anon, authenticated;

drop policy if exists "public read sentence_items" on public.sentence_items;
create policy "public read sentence_items" on public.sentence_items for select to anon, authenticated using (true);

drop policy if exists "public insert sentence_items" on public.sentence_items;
create policy "public insert sentence_items" on public.sentence_items for insert to anon, authenticated with check (true);

drop policy if exists "public update sentence_items" on public.sentence_items;
create policy "public update sentence_items" on public.sentence_items for update to anon, authenticated using (true) with check (true);

drop policy if exists "public delete sentence_items" on public.sentence_items;
create policy "public delete sentence_items" on public.sentence_items for delete to anon, authenticated using (true);
