create table if not exists public.categories (
    id bigint generated by default as identity primary key,
    name text not null,
    emoji text not null default '📁',
    color text not null default '#0ea5e9',
    audio_url text,
    speak_enabled boolean not null default true,
    parent_id bigint references public.categories(id) on delete cascade,
    sort_order integer not null default 0
);

alter table public.categories add column if not exists audio_url text;
alter table public.categories add column if not exists speak_enabled boolean not null default true;

create table if not exists public.words (
    id bigint generated by default as identity primary key,
    category_id bigint not null references public.categories(id) on delete cascade,
    word text not null,
    phrase text,
    emoji text not null default '💬',
    color text not null default '#0ea5e9',
    audio_url text,
    sort_order integer not null default 0
);

alter table public.words add column if not exists audio_url text;

alter table public.categories enable row level security;
alter table public.words enable row level security;

drop policy if exists "public read categories" on public.categories;
create policy "public read categories" on public.categories for select to anon, authenticated using (true);

drop policy if exists "public insert categories" on public.categories;
create policy "public insert categories" on public.categories for insert to anon, authenticated with check (true);

drop policy if exists "public update categories audio" on public.categories;
create policy "public update categories audio" on public.categories for update to anon, authenticated using (true) with check (true);

drop policy if exists "public delete categories" on public.categories;
create policy "public delete categories" on public.categories for delete to anon, authenticated using (true);

drop policy if exists "public read words" on public.words;
create policy "public read words" on public.words for select to anon, authenticated using (true);

drop policy if exists "public insert words" on public.words;
create policy "public insert words" on public.words for insert to anon, authenticated with check (true);

drop policy if exists "public update words audio" on public.words;
create policy "public update words audio" on public.words for update to anon, authenticated using (true) with check (true);

drop policy if exists "public delete words" on public.words;
create policy "public delete words" on public.words for delete to anon, authenticated using (true);

insert into storage.buckets (id, name, public)
values ('word-audio', 'word-audio', true)
on conflict (id) do update set public = true;

drop policy if exists "public read word audio" on storage.objects;
create policy "public read word audio" on storage.objects for select to anon, authenticated using (bucket_id = 'word-audio');

drop policy if exists "public insert word audio" on storage.objects;
create policy "public insert word audio" on storage.objects for insert to anon, authenticated with check (bucket_id = 'word-audio');

drop policy if exists "public update word audio" on storage.objects;
create policy "public update word audio" on storage.objects for update to anon, authenticated using (bucket_id = 'word-audio') with check (bucket_id = 'word-audio');

insert into public.categories (name, emoji, color, parent_id, sort_order)
select seed.name, seed.emoji, seed.color, null, seed.sort_order
from (values
    ('ROZKAZ', '📢', '#ef4444', 1),
    ('ZAPYTANIE', '❓', '#f59e0b', 2),
    ('STWIERDZENIE', '✅', '#3b82f6', 3),
    ('JA', '🧑', '#8b5cf6', 4)
) as seed(name, emoji, color, sort_order)
where not exists (select 1 from public.categories existing where existing.name = seed.name and existing.parent_id is null);

insert into public.categories (name, emoji, color, parent_id, sort_order)
select seed.name, seed.emoji, seed.color, parent_category.id, seed.sort_order
from (values
    ('EMOCJE', '❤️', '#ec4899', 1),
    ('POTRZEBY', '🤲', '#10b981', 2),
    ('BÓL', '🤕', '#f97316', 3),
    ('CZYNNOŚCI', '🏃', '#06b6d4', 4)
) as seed(name, emoji, color, sort_order)
join public.categories parent_category on parent_category.name = 'JA' and parent_category.parent_id is null
where not exists (
    select 1 from public.categories existing
    where existing.name = seed.name and existing.parent_id = parent_category.id
);

insert into public.words (category_id, word, phrase, emoji, color, sort_order)
select category.id, seed.word, seed.phrase, seed.emoji, seed.color, seed.sort_order
from (values
    ('ROZKAZ', 'CZEKAJ', null, '✋', '#ef4444', 1),
    ('ROZKAZ', 'CHODŹ', null, '🚶', '#ef4444', 2),
    ('ZAPYTANIE', 'CO?', null, '❓', '#f59e0b', 1),
    ('ZAPYTANIE', 'GDZIE?', null, '🧭', '#f59e0b', 2),
    ('STWIERDZENIE', 'TAK', null, '👍', '#3b82f6', 1),
    ('STWIERDZENIE', 'NIE', null, '👎', '#3b82f6', 2),
    ('EMOCJE', 'SZCZĘŚLIWA', null, '😊', '#fbbf24', 1),
    ('EMOCJE', 'SMUTNA', null, '😢', '#60a5fa', 2),
    ('EMOCJE', 'ZŁA', null, '😠', '#f87171', 3),
    ('EMOCJE', 'PRZESTRASZONA', null, '😨', '#a78bfa', 4),
    ('POTRZEBY', 'JEDZENIE', null, '🍽️', '#f59e0b', 1),
    ('POTRZEBY', 'PICIE', null, '🥤', '#3b82f6', 2),
    ('POTRZEBY', 'TOALETA', null, '🚻', '#8b5cf6', 3),
    ('POTRZEBY', 'ODPOCZYNEK', null, '🛌', '#6b7280', 4),
    ('BÓL', 'GŁOWA', null, '🤯', '#f87171', 1),
    ('BÓL', 'BRZUCH', null, '🤰', '#fb923c', 2),
    ('BÓL', 'NOGA', null, '🦵', '#a78bfa', 3),
    ('BÓL', 'RĘKA', null, '🖐️', '#60a5fa', 4),
    ('CZYNNOŚCI', 'CHCĘ', null, '👍', '#22c55e', 1),
    ('CZYNNOŚCI', 'NIE CHCĘ', null, '👎', '#ef4444', 2),
    ('CZYNNOŚCI', 'ŚPIĘ', null, '😴', '#818cf8', 3),
    ('CZYNNOŚCI', 'WSTAJĘ', null, '🧍', '#fbbf24', 4)
) as seed(category_name, word, phrase, emoji, color, sort_order)
join public.categories category on category.name = seed.category_name
where not exists (
    select 1 from public.words existing
    where existing.category_id = category.id and existing.word = seed.word
);
